# HealthBar Configuration
format: "&f%damager - &c[%health&c]"
health-format:
  health-used: "&c|"
  health-not-used: "&4|"

disabled-worlds:
- my_world_name

disabled-entities:
- ender_dragon
- wither
